# Generated by Django 2.1.3 on 2018-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content', models.CharField(max_length=50)),
                ('cTime', models.DateField()),
                ('publishAuthor', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('headLine', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=100)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('author', models.DateField(max_length=20)),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'new',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=17)),
                ('country', models.CharField(max_length=20)),
                ('idNumber', models.IntegerField()),
                ('userToken', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
