# Generated by Django 2.1.3 on 2018-12-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181224_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='headLine',
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
