# Generated by Django 2.1.3 on 2018-12-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_new_articleauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='articleAuthor',
            field=models.CharField(max_length=20),
        ),
    ]
