# Generated by Django 2.1.3 on 2018-12-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_new_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
            ],
        ),
    ]
