# Generated by Django 2.1.3 on 2018-12-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_militarynew'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='militarynew',
            table='military',
        ),
    ]
