# Generated by Django 2.1.3 on 2019-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20181230_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfricaNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('newtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'AfricaNew',
            },
        ),
        migrations.CreateModel(
            name='AntarcticaNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('newtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'AntarcticaNew',
            },
        ),
        migrations.CreateModel(
            name='AsiaNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('newtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'AsiaNew',
            },
        ),
        migrations.CreateModel(
            name='EuropeNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('newtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'EuropeNew',
            },
        ),
        migrations.CreateModel(
            name='NorthAmericaNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('newtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'NorthAmericaNew',
            },
        ),
        migrations.CreateModel(
            name='OceaniaNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('newtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'OceaniaNew',
            },
        ),
        migrations.CreateModel(
            name='SouthAmericaNew',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('commentNumber', models.IntegerField()),
                ('publishTime', models.DateField()),
                ('articleAuthor', models.CharField(max_length=20)),
                ('readerNumber', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=10)),
                ('newtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'SouthAmericaNew',
            },
        ),
        migrations.DeleteModel(
            name='MilitaryNew',
        ),
    ]
